#!/usr/bin/env bash
#Write a Bash script that displays Best School 10 times, but for the 9th iteration, displays Best School and then Hi on a new line.
counter=0
while [ $counter -ne 10 ]
do
	((counter++))
	if [ $counter -eq 9 ]
	then
		echo "Hi"
	else
		echo "Best School"
	fi
done
