#!/usr/bin/env bash
# Write a Bash script that loops from 1 to 10
counter=0
while [ $counter -ne 10 ]
do
	((counter++))
	if [ $counter -eq 4 ]
	then
		echo "bad luck"
	elif [ $counter -eq 8 ]
	then
		echo "good luck"
	else
		echo "Best School"
	fi
done
