#!/usr/bin/env bash
#Superstitious numbers
counter=0
while [ $counter -ne 20 ]
do
	((counter++))
	echo $counter
	case $counter in

	4)
	echo "bad luck from China"
	;;

	9)
	echo "bad luck from Japan"
	;;

	17)
	echo "bad luck from Italy"
	;;
	esac
done
