#!/usr/bin/env bash
#Info about "School" file
find . -name "school*" -print0 | while read -rd $'\0' file
do
    if [ -e "$file" ]
    then
        echo "school file exists"
        if [ -s "$file" ]
        then
            echo "school file is not empty"
        else
            echo "school file is empty"
        fi
        if [ -f "$file" ]
        then
            echo "school is a regular file"
        fi
    else
        echo "school file does not exist"
    fi
done
