#!/usr/bin/env bash
#Multiple traps
echo $$ > /var/run/myscript.pid
trap "echo 'I hate the kill command'" SIGTERM
trap "echo 'Y U no love me?!' | rm /var/run/myscript.pid; exit" SIGINT
trap "rm /var/run/myscript.pid; exit" SIGQUIT
while true
do
    echo "To infinity and beyond"
done
