#!/usr/bin/env bash
#Multiple traps
remove="rm /var/run/myscript.pid"
echo $$ > /var/run/myscript.pid
trap "echo 'I hate the kill command'" SIGTERM
trap "echo 'Y U no love me?!'; "$remove"; exit" SIGINT
trap "$remove"; exit" SIGQUIT
while true
do
    echo "To infinity and beyond"
done
