#!/usr/bin/env bash
#Multiple traps
echo $$ > /var/run/myscript.pid
trap "echo 'I hate the kill command'; rm -f /var/run/myscript.pid, exit 1" SIGTERM
trap "echo 'Y U no love me?!'" SIGINT
trap "rm -f /var/run/myscript.pid; exit 1" SIGQUIT
while true
do
    echo "To infinity and beyond"
done
