#!/usr/bin/env bash
#Daemon
param=$1
case $param in
    'start')
        echo manage_my_process started ;
        echo $$ > /var/run/my_process.pid ;
	bash ./manage_my_process &
    ;;
    'stop')
	echo manage_my_process stopped ;
        rm -f "/var/run/my_process.pid" ;
	pkill "$(pgrep -f "manage_my_process")" ;
    ;;
    'restart')
	echo $$ > /var/run/my_process.pid ;
	echo manage_my_process restarted ;
	pkill "$(pgrep -f "manage_my_process")" ;
	rm -f "/var/run/my_process.pid" ;
	bash ./manage_my_process &
    ;;
    *)
        echo "Usage: manage_my_process {start|stop|restart}" ;
    ;;
esac
